### ISSUE TITLE
Dockerised TON node: a lot of 651 errors

### ISSUE THREAD

**Issue by fmira21** [ton-blockchain/ton#663]
Hi guys!

I have just started the TON validator node in Testnet. It is running on an `m5ad.2xlarge` EC2 instance, I use your Docker setup:

ghcr.io/ton-blockchain/ton:latest

Compose configuration:

```
version: '3'

services:
  ton:
    image: ghcr.io/ton-blockchain/ton:latest
    restart: always
    ports:
      - 43678:43678
      - 43679:43679
    volumes:
      - /ton-node/db:/var/ton-work/db
    environment:
      GCONFURL: "https://ton.org/testnet-global.config.json"
      CONSOLE_PORT: "43678"
      PUBLIC_IP: "my_ec2_ip"
      LITESERVER: "true"
      LITE_PORT: "43679"
```

But the node cannot start, as far as I can see, and returns 651 errors:

```
[+] Running validator-engine
[ 3][t 1][2023-03-29 20:07:26.506682322][validator-engine.cpp:1294][!validator-engine]	found init block [ w=-1 s=9223372036854775808 seq=5176527 SoPLqMe9Dz26YJPOGDOHApTSe5i0kXFtRmRh/zPMGuI= xRaxgUwgTXYFb16YnR+Q+VVsczLl6jmYwvzhQ/ncrh4= ]
[ 3][t 4][2023-03-29 20:07:26.528522341][manager.cpp:1496][!manager]	failed to load blocks from import dir: [PosixError : No such file or directory : 2 : File "/var/ton-work/db/import" can't be opened for reading]
[ 3][t 2][2023-03-29 20:07:26.548587839][manager-init.cpp:35][!reiniter]	init_block_id=[ w=-1 s=9223372036854775808 seq=5176527 SoPLqMe9Dz26YJPOGDOHApTSe5i0kXFtRmRh/zPMGuI= xRaxgUwgTXYFb16YnR+Q+VVsczLl6jmYwvzhQ/ncrh4= ]
[ 2][t 2][2023-03-29 20:07:26.549769686][manager-init.cpp:86][!downloadproofreq]	failed to download proof link: [Error : 651 : no nodes]
[ 2][t 7][2023-03-29 20:07:27.550617772][manager-init.cpp:86][!downloadproofreq]	failed to download proof link: [Error : 651 : no nodes]
[ 2][t 1][2023-03-29 20:07:28.551770963][manager-init.cpp:86][!downloadproofreq]	failed to download proof link: [Error : 651 : no nodes]
[ 2][t 1][2023-03-29 20:07:29.552310513][manager-init.cpp:86][!downloadproofreq]	failed to download proof link: [Error : 651 : no nodes]
```

What am I doing wrong?
Thank you in advance!
