### ISSUE TITLE
Proxy is not working in Docker

### ISSUE THREAD

**Issue by ZergsLaw** [ton-blockchain/ton#798]
Displays errors in logs of unknown origin, and also some sites in the *.ton zone do not work

```log
ton-proxy  | [ 2][t 2][2023-11-04 11:30:21.999243325][TonlibClient.cpp:2716][!tonlibclient][&!config->ignore_cache_]	Unknown LastBlockState: [Error : 0 : Unknown key]
ton-proxy  | [ 1][t 0][2023-11-04 11:30:34.376159254][TcpListener.cpp:62][!TcpListener[port:8080]]	Accept
ton-proxy  | [ 1][t 0][2023-11-04 11:31:42.366194530][http-connection.cpp:81][!inhttpconn]	loop() failed: [PosixError : Broken pipe : 32 : Error on [fd:14]]
```

That there will be no errors and the tutorial will work

Errors in the logs and opening the site http://just-for-test.ton does not work

It is possible to run inside Docker proxy and run it via docker compose

v2023.10

ubuntu 22.04

Dockerfile 
```Dockerfile
FROM ubuntu:22.04 as builder

RUN apt-get update && apt-get install -y unzip

ADD https://github.com/ton-blockchain/ton/releases/download/v2023.10/ton-linux-x86_64.zip /

RUN unzip /ton-linux-x86_64.zip -d /ton/

FROM ubuntu:22.04

RUN apt-get update && \
	apt-get install -y openssl wget libatomic1 && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /ton/rldp-http-proxy /usr/local/bin/
COPY entrypoint.sh entrypoint.sh

RUN chmod +x /usr/local/bin/rldp-http-proxy
RUN chmod +x entrypoint.sh

ENV PORT 8080
ENV SERVER_IP 127.0.0.1
ENV ADNL_PORT 3333
ENV CONFIG_PATH "/volume/global.config.json"

ENTRYPOINT ["./entrypoint.sh"]
```

entrypoint.sh
```sh
#!/bin/bash
set -x -e -o pipefail

chmod 600 /app/keyring/*

rldp-http-proxy \
      -p $PORT \
      -a $SERVER_IP:$ADNL_PORT \
      -C $CONFIG_PATH \
      -A $ADNL_ADDRESS \
      -P NO \
      -R '*'@$REMOTE_ADDR
```

docker-compose.yml
```yaml
version: "3.9"

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

services:

  proxy-svc:
    build:
      context: "proxy"
      dockerfile: "Dockerfile"
    image: "ton/proxy:dev"
    container_name: "ton-proxy"
    restart: "always"
    networks:
      vpcbr:
        ipv4_address: 172.20.0.2
    environment:
      PORT: "8080"
      ADNL_PORT: "3333"
      SERVER_IP: "188.242.40.238"
      CONFIG_PATH: "/app/global.config.json"
      ADNL_ADDRESS: "w2enenb6d2nxblrtymwgskpcaidvrkexhlish47r3z43plexmz7xpae"
      REMOTE_ADDR: "172.20.0.2:80"
    volumes:
      - "./proxy/global.config.json:/app/global.config.json"
      - "./generate-random-id/keyring:/app/keyring"
    ports:
      - "8080:8080"
      - "3333:3333"

```

**Comment by ton-devops** [comment]
@ZergsLaw  ton-proxy work to docker

* example ci-cd code https://github.com/tonstakers/ton-proxy/blob/master/docker-ton-proxy.ci
* DockerHub  artefact - https://hub.docker.com/r/tonstakers/ton-proxy/tags

example code compose 
```
services:
  tonproxy:
    image: tonstakers/ton-proxy:latest
    container_name: tonproxy
    hostname: tonproxy
    restart: always
    volumes:
      - /opt/tonproxy/keyring:/opt/ton-proxy/keyring
    command: "rldp-http-proxy -p 8080 -a ip:3333 -C global.config.json -A adnl -d -v3"
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '2'
```
